/**
 * NUR Lingo — Ընդլայնված Բառարան v2
 * 100+ entries: Ընտանիք, Կենցաղային, Ամենօրյա, Շրջապատ, Ուսուցում, Երկիր
 */
export type GrammarType = "noun"|"verb"|"adjective"|"adverb"|"pronoun"|"preposition"|"conjunction"|"interjection"|"numeral"|"particle";
export type SemanticCategory = "home_living"|"food_drink"|"family_relationships"|"travel_movement"|"emotions_feelings"|"time_calendar"|"colors_appearance"|"nature_environment"|"work_profession"|"education_learning"|"health_body"|"numbers_math"|"greetings_politeness"|"verbs_motion"|"verbs_communication"|"verbs_cognition"|"pronouns_core"|"adjectives_basic"|"clothing"|"weather"|"animals"|"city_transport"|"daily_routine"|"shopping"|"hobbies"|"technology";
export interface ExampleSentence { armenian:string; english:string; level:1|2|3; acceptable_variants?:string[]; }
export interface LexiconEntry { id:string; word:string; english:string[]; synonyms:string[]; antonyms?:string[]; grammar_type:GrammarType; difficulty:1|2|3|4|5; examples:ExampleSentence[]; embedding_group:SemanticCategory; lesson_tags:string[]; related_forms?:string[]; notes?:string; frequency_rank?:number; gender_note?:string; }
export interface SentencePattern { id:string; english_template:string; armenian_variants:string[]; grammar_note?:string; difficulty:1|2|3|4|5; lesson_tags:string[]; semantic_group:string; }

export const LEXICON: LexiconEntry[] = [
  // PRONOUNS
  {id:"pron_001",word:"ես",english:["I","me"],synonyms:[],grammar_type:"pronoun",difficulty:1,embedding_group:"pronouns_core",lesson_tags:["lesson_1"],frequency_rank:1,examples:[{armenian:"Ես հայ եմ",english:"I am Armenian",level:1,acceptable_variants:["Հայ եմ"]}]},
  {id:"pron_002",word:"դու",english:["you (singular)"],synonyms:[],grammar_type:"pronoun",difficulty:1,embedding_group:"pronouns_core",lesson_tags:["lesson_1"],frequency_rank:3,examples:[{armenian:"Դու լավ ես",english:"You are fine",level:1}]},
  {id:"pron_003",word:"նա",english:["he","she","it"],synonyms:[],grammar_type:"pronoun",difficulty:1,embedding_group:"pronouns_core",lesson_tags:["lesson_1"],frequency_rank:5,notes:"Հայերենում երրորդ դեմքում սեռ չկա",examples:[{armenian:"Նա գնում է",english:"He/She is going",level:1}]},
  {id:"pron_004",word:"մենք",english:["we"],synonyms:[],grammar_type:"pronoun",difficulty:1,embedding_group:"pronouns_core",lesson_tags:["lesson_1"],frequency_rank:8,examples:[{armenian:"Մենք հայ ենք",english:"We are Armenian",level:1}]},
  {id:"pron_005",word:"դուք",english:["you (plural/formal)"],synonyms:[],grammar_type:"pronoun",difficulty:1,embedding_group:"pronouns_core",lesson_tags:["lesson_1"],frequency_rank:10,examples:[{armenian:"Դուք հայ եք",english:"You are Armenian (pl.)",level:1}]},
  {id:"pron_006",word:"նրանք",english:["they"],synonyms:[],grammar_type:"pronoun",difficulty:1,embedding_group:"pronouns_core",lesson_tags:["lesson_1"],frequency_rank:9,examples:[{armenian:"Նրանք Երևանում են",english:"They are in Yerevan",level:1}]},
  // FAMILY
  {id:"fam_001",word:"մայր",english:["mother"],synonyms:["մամա","մայրիկ"],grammar_type:"noun",difficulty:1,embedding_group:"family_relationships",lesson_tags:["lesson_4"],frequency_rank:18,related_forms:["մոր","մայրս","մայրիկս"],notes:"մայրս = իմ մայրը",examples:[{armenian:"Մայրս բժշկուհի է",english:"My mother is a doctor",level:1,acceptable_variants:["Իմ մայրը բժիշկ է","Մայրիկս բժշկուհի է","Մայրս բժիշկ է"]}]},
  {id:"fam_002",word:"հայր",english:["father"],synonyms:["բաբա","հայրիկ"],grammar_type:"noun",difficulty:1,embedding_group:"family_relationships",lesson_tags:["lesson_4"],frequency_rank:19,related_forms:["հոր","հայրս","հայրիկիս"],notes:"հայրս = իմ հայրը",examples:[{armenian:"Հայրս ուսուցիչ է",english:"My father is a teacher",level:1,acceptable_variants:["Իմ հայրը ուսուցիչ է"]}]},
  {id:"fam_003",word:"մայրիկ",english:["mom","mommy"],synonyms:["մայր","մամա"],grammar_type:"noun",difficulty:1,embedding_group:"family_relationships",lesson_tags:["lesson_4"],frequency_rank:22,related_forms:["մայրիկիս","մայրիկս"],examples:[{armenian:"Մայրիկս շատ լավ է",english:"My mom is very kind",level:1}]},
  {id:"fam_004",word:"հայրիկ",english:["dad","daddy"],synonyms:["հայր","բաբա"],grammar_type:"noun",difficulty:1,embedding_group:"family_relationships",lesson_tags:["lesson_4"],frequency_rank:23,related_forms:["հայրիկս"],examples:[{armenian:"Հայրիկս տուն եկավ",english:"My dad came home",level:1}]},
  {id:"fam_005",word:"քույր",english:["sister"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"family_relationships",lesson_tags:["lesson_4"],frequency_rank:30,related_forms:["քրոջ","քույրս"],examples:[{armenian:"Քույրս ուսանող է",english:"My sister is a student",level:1}]},
  {id:"fam_006",word:"եղբայր",english:["brother"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"family_relationships",lesson_tags:["lesson_4"],frequency_rank:31,related_forms:["եղբոր","եղբայրս"],examples:[{armenian:"Եղբայրս Երևանում է",english:"My brother is in Yerevan",level:1}]},
  {id:"fam_007",word:"պապիկ",english:["grandfather","grandpa"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"family_relationships",lesson_tags:["lesson_4"],frequency_rank:35,examples:[{armenian:"Պապիկս 70 տարեկան է",english:"My grandfather is 70 years old",level:2}]},
  {id:"fam_008",word:"տատիկ",english:["grandmother","grandma"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"family_relationships",lesson_tags:["lesson_4"],frequency_rank:36,examples:[{armenian:"Տատիկս հաց է թխում",english:"My grandma is baking bread",level:2}]},
  {id:"fam_009",word:"երեխա",english:["child","kid"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"family_relationships",lesson_tags:["lesson_4"],frequency_rank:28,examples:[{armenian:"Երեխան փոքր է",english:"The child is small",level:1}]},
  {id:"fam_010",word:"ընկեր",english:["friend"],synonyms:["բարեկամ"],grammar_type:"noun",difficulty:1,embedding_group:"family_relationships",lesson_tags:["lesson_4"],frequency_rank:22,related_forms:["ընկերոջ","ընկերս"],examples:[{armenian:"Ընկերս լավ մարդ է",english:"My friend is a good person",level:1,acceptable_variants:["Իմ ընկերը լավ մարդ է"]}]},
  {id:"fam_011",word:"ամուսին",english:["husband"],synonyms:[],grammar_type:"noun",difficulty:2,embedding_group:"family_relationships",lesson_tags:["lesson_6"],frequency_rank:45,examples:[{armenian:"Ամուսինս Երևանում է աշխատում",english:"My husband works in Yerevan",level:2}]},
  {id:"fam_012",word:"կին",english:["wife"],synonyms:[],grammar_type:"noun",difficulty:2,embedding_group:"family_relationships",lesson_tags:["lesson_6"],frequency_rank:46,examples:[{armenian:"Կինս նկարիչ է",english:"My wife is an artist",level:2}]},
  // HOME
  {id:"home_001",word:"տուն",english:["home","house"],synonyms:["բնակարան"],grammar_type:"noun",difficulty:1,embedding_group:"home_living",lesson_tags:["lesson_2"],frequency_rank:12,related_forms:["տան","տնից","տներ"],examples:[{armenian:"Ես գնում եմ տուն",english:"I am going home",level:1,acceptable_variants:["Ես տուն եմ գնում","Տուն եմ գնում"]}]},
  {id:"home_002",word:"սենյակ",english:["room","bedroom"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"home_living",lesson_tags:["lesson_2"],frequency_rank:38,related_forms:["սենյակի","սենյակում"],examples:[{armenian:"Իմ սենյակում եմ",english:"I am in my room",level:1}]},
  {id:"home_003",word:"խոհանոց",english:["kitchen"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"home_living",lesson_tags:["lesson_2"],frequency_rank:42,examples:[{armenian:"Մայրս խոհանոցում է",english:"My mom is in the kitchen",level:1}]},
  {id:"home_004",word:"դուռ",english:["door"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"home_living",lesson_tags:["lesson_2"],frequency_rank:33,examples:[{armenian:"Դուռը բաց է",english:"The door is open",level:1}]},
  {id:"home_005",word:"պատուհան",english:["window"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"home_living",lesson_tags:["lesson_2"],frequency_rank:37,examples:[{armenian:"Պատուհանը փակ է",english:"The window is closed",level:1}]},
  {id:"home_006",word:"մահճակալ",english:["bed"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"home_living",lesson_tags:["lesson_2"],frequency_rank:40,examples:[{armenian:"Ես քնում եմ մահճակալին",english:"I am sleeping in bed",level:1}]},
  {id:"home_007",word:"սեղան",english:["table","desk"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"home_living",lesson_tags:["lesson_2"],frequency_rank:36,examples:[{armenian:"Գիրքը սեղանին է",english:"The book is on the table",level:1}]},
  {id:"home_008",word:"աթոռ",english:["chair"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"home_living",lesson_tags:["lesson_2"],frequency_rank:39,examples:[{armenian:"Նստիր աթոռին",english:"Sit on the chair",level:1}]},
  {id:"home_009",word:"հեռուստացույց",english:["TV","television"],synonyms:["տելեվիզոր"],grammar_type:"noun",difficulty:1,embedding_group:"home_living",lesson_tags:["lesson_2"],frequency_rank:30,examples:[{armenian:"Հեռուստացույց ենք նայում",english:"We are watching TV",level:1}]},
  // FOOD
  {id:"food_001",word:"ջուր",english:["water"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:15,related_forms:["ջրի","ջրից"],examples:[{armenian:"Ես ջուր եմ խմում",english:"I am drinking water",level:1}]},
  {id:"food_002",word:"հաց",english:["bread","food"],synonyms:["կերակուր"],grammar_type:"noun",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:20,examples:[{armenian:"Ես հաց եմ ուտում",english:"I am eating bread",level:1}]},
  {id:"food_003",word:"կաթ",english:["milk"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:32,examples:[{armenian:"Երեխան կաթ է խմում",english:"The child is drinking milk",level:1}]},
  {id:"food_004",word:"ձու",english:["egg","eggs"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:35,examples:[{armenian:"Առավոտյան ձու ենք ուտում",english:"We eat eggs in the morning",level:1}]},
  {id:"food_005",word:"միս",english:["meat"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:38,examples:[{armenian:"Խորովածը միս է",english:"Խորոված is meat",level:1}]},
  {id:"food_006",word:"մածուն",english:["yogurt (Armenian մածուն)"],synonyms:["բան"],grammar_type:"noun",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:40,notes:"Traditional Armenian yogurt — cultural staple",examples:[{armenian:"Մածունը համով է",english:"Մածուն is tasty",level:1}]},
  {id:"food_007",word:"միրգ",english:["fruit"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:36,examples:[{armenian:"Ես միրգ եմ սիրում",english:"I love fruit",level:1}]},
  {id:"food_008",word:"բանջարեղեն",english:["vegetable"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:37,examples:[{armenian:"Բանջարեղենը առողջարար է",english:"Vegetables are healthy",level:1}]},
  {id:"food_009",word:"սուրջ",english:["coffee"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:25,notes:"Armenian coffee culture is central to daily life",examples:[{armenian:"Ես հայկական սուրջ եմ խմում",english:"I drink Armenian coffee",level:1}]},
  {id:"food_010",word:"թեյ",english:["tea"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:26,examples:[{armenian:"Ես թեյ եմ խմում",english:"I am drinking tea",level:1}]},
  {id:"food_011",word:"համով",english:["tasty","delicious"],synonyms:[],grammar_type:"adjective",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:30,examples:[{armenian:"Խորովածը շատ համով է",english:"The barbecue is very tasty",level:1}]},
  {id:"food_012",word:"նուռ",english:["pomegranate"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:44,notes:"NUR Lingo mascot named after pomegranate — Armenia's national symbol",examples:[{armenian:"Նուռը Հայաստանի խորհրդանիշն է",english:"The pomegranate is the symbol of Armenia",level:2}]},
  {id:"food_013",word:"ծիրան",english:["apricot"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:45,notes:"Armenia is historically the birthplace of the apricot (Prunus armeniaca)",examples:[{armenian:"Հայաստանը ծիրանով է հայտնի",english:"Armenia is famous for its apricots",level:2}]},
  // DAILY ROUTINE
  {id:"daily_001",word:"առավոտ",english:["morning"],synonyms:["այգ"],grammar_type:"noun",difficulty:1,embedding_group:"daily_routine",lesson_tags:["lesson_6"],frequency_rank:20,examples:[{armenian:"Բարի առավոտ",english:"Good morning",level:1,acceptable_variants:["Բարի լույս"]}]},
  {id:"daily_002",word:"կեսօր",english:["afternoon","noon"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"daily_routine",lesson_tags:["lesson_6"],frequency_rank:25,examples:[{armenian:"Բարի կեսօր",english:"Good afternoon",level:1}]},
  {id:"daily_003",word:"երեկո",english:["evening"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"daily_routine",lesson_tags:["lesson_6"],frequency_rank:22,examples:[{armenian:"Բարի երեկո",english:"Good evening",level:1}]},
  {id:"daily_004",word:"գիշեր",english:["night"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"daily_routine",lesson_tags:["lesson_6"],frequency_rank:23,examples:[{armenian:"Բարի գիշեր",english:"Good night",level:1}]},
  {id:"daily_005",word:"օր",english:["day"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"daily_routine",lesson_tags:["lesson_6"],frequency_rank:14,related_forms:["օրվա","օրից","օրեր"],examples:[{armenian:"Այսօր լավ օր է",english:"Today is a good day",level:1}]},
  {id:"daily_006",word:"այսօր",english:["today"],synonyms:[],grammar_type:"adverb",difficulty:1,embedding_group:"daily_routine",lesson_tags:["lesson_6"],frequency_rank:13,examples:[{armenian:"Այսօր արև կա",english:"It is sunny today",level:1}]},
  {id:"daily_007",word:"վաղը",english:["tomorrow"],synonyms:[],grammar_type:"adverb",difficulty:1,embedding_group:"daily_routine",lesson_tags:["lesson_6"],frequency_rank:16,examples:[{armenian:"Վաղը դպրոց եմ գնում",english:"I am going to school tomorrow",level:1}]},
  {id:"daily_008",word:"երեկ",english:["yesterday"],synonyms:[],grammar_type:"adverb",difficulty:1,embedding_group:"daily_routine",lesson_tags:["lesson_6"],frequency_rank:17,examples:[{armenian:"Երեկ տանն էի",english:"I was at home yesterday",level:1}]},
  {id:"daily_009",word:"զարթնել",english:["to wake up"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"daily_routine",lesson_tags:["lesson_6"],frequency_rank:35,related_forms:["զարթնում եմ","զարթնեցի"],examples:[{armenian:"Ես վաղ եմ զարթնում",english:"I wake up early",level:1}]},
  {id:"daily_010",word:"քնել",english:["to sleep"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"daily_routine",lesson_tags:["lesson_6"],frequency_rank:33,related_forms:["քնում եմ","քնեցի"],examples:[{armenian:"Ես ուզում եմ քնել",english:"I want to sleep",level:1}]},
  {id:"daily_011",word:"լվացվել",english:["to wash","to bathe"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"daily_routine",lesson_tags:["lesson_6"],frequency_rank:40,related_forms:["լվացվում եմ"],examples:[{armenian:"Առավոտյան լվացվում եմ",english:"I wash up in the morning",level:1}]},
  {id:"daily_012",word:"աշխատել",english:["to work"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"work_profession",lesson_tags:["lesson_7"],frequency_rank:14,related_forms:["աշխատում եմ","աշխատեցի"],examples:[{armenian:"Ես աշխատում եմ Երևանում",english:"I work in Yerevan",level:1}]},
  // CORE VERBS
  {id:"verb_001",word:"գնալ",english:["to go","to leave"],synonyms:["մեկնել"],grammar_type:"verb",difficulty:1,embedding_group:"verbs_motion",lesson_tags:["lesson_2"],frequency_rank:7,related_forms:["գնում եմ","գնում ես","գնում է","գնացի","գնաց","կգնամ"],examples:[{armenian:"Ես գնում եմ տուն",english:"I am going home",level:1,acceptable_variants:["Ես տուն եմ գնում","Տուն եմ գնում"]}]},
  {id:"verb_002",word:"գալ",english:["to come"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"verbs_motion",lesson_tags:["lesson_2"],frequency_rank:9,related_forms:["գալիս եմ","եկա","եկավ","կգամ"],examples:[{armenian:"Ես գալիս եմ",english:"I am coming",level:1}]},
  {id:"verb_003",word:"լինել",english:["to be","to exist","to become"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"verbs_cognition",lesson_tags:["lesson_1"],frequency_rank:2,related_forms:["եմ","ես","է","ենք","եք","են","էի","էր","եղա","եղավ","կլինեմ"],examples:[{armenian:"Ես ուսանող եմ",english:"I am a student",level:1},{armenian:"Մայրս բժշկուհի է",english:"My mother is a doctor",level:1}]},
  {id:"verb_004",word:"ուտել",english:["to eat"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:28,related_forms:["ուտում եմ","ուտում ես","ուտում է","կերա","կերավ"],examples:[{armenian:"Ես հաց եմ ուտում",english:"I am eating bread",level:1,acceptable_variants:["Ես ուտում եմ հաց","Հաց եմ ուտում"]}]},
  {id:"verb_005",word:"խմել",english:["to drink"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:29,related_forms:["խմում եմ","խմում է","խմեցի"],examples:[{armenian:"Ես սուրջ եմ խմում",english:"I am drinking coffee",level:1}]},
  {id:"verb_006",word:"խոսել",english:["to speak","to talk"],synonyms:["ասել"],grammar_type:"verb",difficulty:1,embedding_group:"verbs_communication",lesson_tags:["lesson_2"],frequency_rank:20,related_forms:["խոսում եմ","խոսում ես","խոսում է","խոսեցի"],examples:[{armenian:"Ես հայերեն եմ խոսում",english:"I speak Armenian",level:1}]},
  {id:"verb_007",word:"սիրել",english:["to love","to like"],synonyms:["հավանել"],grammar_type:"verb",difficulty:1,embedding_group:"emotions_feelings",lesson_tags:["lesson_4"],frequency_rank:16,related_forms:["սիրում եմ","սիրում ես","սիրում է","սիրեցի"],examples:[{armenian:"Ես սիրում եմ Հայաստանը",english:"I love Armenia",level:1,acceptable_variants:["Հայաստանը սիրում եմ"]}]},
  {id:"verb_008",word:"կարդալ",english:["to read"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"education_learning",lesson_tags:["lesson_5"],frequency_rank:35,related_forms:["կարդում եմ","կարդում ես","կարդացի"],examples:[{armenian:"Ես գիրք եմ կարդում",english:"I am reading a book",level:1,acceptable_variants:["Ես կարդում եմ գիրք","Գիրք եմ կարդում"]}]},
  {id:"verb_009",word:"գրել",english:["to write"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"education_learning",lesson_tags:["lesson_5"],frequency_rank:32,related_forms:["գրում եմ","գրում ես","գրեցի"],examples:[{armenian:"Ես նամակ եմ գրում",english:"I am writing a letter",level:1}]},
  {id:"verb_010",word:"ուզել",english:["to want","to wish"],synonyms:["ցանկանալ"],grammar_type:"verb",difficulty:1,embedding_group:"emotions_feelings",lesson_tags:["lesson_3"],frequency_rank:13,related_forms:["ուզում եմ","ուզում ես","ուզեցի"],examples:[{armenian:"Ես ջուր եմ ուզում",english:"I want water",level:1,acceptable_variants:["Ջուր եմ ուզում"]}]},
  {id:"verb_011",word:"ապրել",english:["to live","to reside"],synonyms:["բնակվել"],grammar_type:"verb",difficulty:1,embedding_group:"home_living",lesson_tags:["lesson_2"],frequency_rank:21,related_forms:["ապրում եմ","ապրում ես","ապրում է","ապրեցի"],examples:[{armenian:"Ես Երևանում եմ ապրում",english:"I live in Yerevan",level:1,acceptable_variants:["Ես ապրում եմ Երևանում","Երևանում եմ ապրում"]}]},
  {id:"verb_012",word:"հասկանալ",english:["to understand"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"verbs_cognition",lesson_tags:["lesson_1"],frequency_rank:15,related_forms:["հասկանում եմ","հասկանում ես","հասկացա"],examples:[{armenian:"Ես հասկանում եմ",english:"I understand",level:1,acceptable_variants:["Հասկանում եմ"]}]},
  {id:"verb_013",word:"սովորել",english:["to learn","to study"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"education_learning",lesson_tags:["lesson_5"],frequency_rank:20,related_forms:["սովորում եմ","սովորում ես","սովորեցի"],examples:[{armenian:"Ես հայերեն եմ սովորում",english:"I am learning Armenian",level:1}]},
  {id:"verb_014",word:"տալ",english:["to give"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"verbs_communication",lesson_tags:["lesson_5"],frequency_rank:18,related_forms:["տալիս եմ","տալիս ես","տվեցի","տվեց"],examples:[{armenian:"Ինձ ջուր տուր",english:"Give me water",level:2}]},
  {id:"verb_015",word:"տեսնել",english:["to see","to look","to watch"],synonyms:["նայել"],grammar_type:"verb",difficulty:1,embedding_group:"verbs_cognition",lesson_tags:["lesson_2"],frequency_rank:17,related_forms:["տեսնում եմ","տեսնում ես","տեսա","կտեսնեմ"],examples:[{armenian:"Ես հեռուստացույց եմ նայում",english:"I am watching TV",level:1}]},
  // CITY & ENVIRONMENT
  {id:"city_001",word:"Հայաստան",english:["Armenia"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"nature_environment",lesson_tags:["lesson_1"],frequency_rank:10,related_forms:["Հայաստանի","Հայաստանից","Հայաստանում"],examples:[{armenian:"Ես սիրում եմ Հայաստանը",english:"I love Armenia",level:1}]},
  {id:"city_002",word:"Երևան",english:["Yerevan"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"city_transport",lesson_tags:["lesson_1"],frequency_rank:11,related_forms:["Երևանի","Երևանից","Երևանում"],examples:[{armenian:"Ես ապրում եմ Երևանում",english:"I live in Yerevan",level:1}]},
  {id:"city_003",word:"փողոց",english:["street","road"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"city_transport",lesson_tags:["lesson_7"],frequency_rank:28,examples:[{armenian:"Փողոցը մեծ է",english:"The street is big",level:1}]},
  {id:"city_004",word:"խանութ",english:["store","shop"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"shopping",lesson_tags:["lesson_7"],frequency_rank:30,examples:[{armenian:"Խանութ եմ գնում",english:"I am going to the store",level:1}]},
  {id:"city_005",word:"գին",english:["price"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"shopping",lesson_tags:["lesson_7"],frequency_rank:35,examples:[{armenian:"Ի՞նչ արժե",english:"How much does it cost?",level:1}]},
  {id:"city_006",word:"շուկա",english:["market","bazaar"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"shopping",lesson_tags:["lesson_7"],frequency_rank:32,examples:[{armenian:"Շուկա եմ գնում",english:"I am going to the market",level:1}]},
  {id:"city_007",word:"ավտոբուս",english:["bus"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"city_transport",lesson_tags:["lesson_7"],frequency_rank:33,examples:[{armenian:"Ավտոբուսով եմ գնում",english:"I am going by bus",level:1}]},
  {id:"city_008",word:"մետրո",english:["subway","metro"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"city_transport",lesson_tags:["lesson_7"],frequency_rank:36,examples:[{armenian:"Երևանը մետրո ունի",english:"Yerevan has a metro",level:1}]},
  {id:"city_009",word:"այգի",english:["park"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"nature_environment",lesson_tags:["lesson_7"],frequency_rank:38,examples:[{armenian:"Այգի ենք գնում",english:"We are going to the park",level:1}]},
  // NATURE
  {id:"nat_001",word:"արև",english:["sun"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"nature_environment",lesson_tags:["lesson_8"],frequency_rank:28,examples:[{armenian:"Արևը փայլում է",english:"The sun is shining",level:1}]},
  {id:"nat_002",word:"անձրև",english:["rain"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"weather",lesson_tags:["lesson_8"],frequency_rank:30,examples:[{armenian:"Անձրև է գալիս",english:"It is raining",level:1}]},
  {id:"nat_003",word:"ծով",english:["lake","sea"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"nature_environment",lesson_tags:["lesson_8"],frequency_rank:35,notes:"Sevan is the famous Armenian lake",examples:[{armenian:"Սևանա լիճը գեղեցիկ է",english:"Lake Sevan is beautiful",level:1}]},
  {id:"nat_004",word:"լեռ",english:["mountain"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"nature_environment",lesson_tags:["lesson_8"],frequency_rank:32,notes:"Aragats and Ararat are iconic Armenian mountains",examples:[{armenian:"Արարատ լեռը շատ մեծ է",english:"Mount Ararat is very big",level:1}]},
  {id:"nat_005",word:"ծառ",english:["tree"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"nature_environment",lesson_tags:["lesson_8"],frequency_rank:38,examples:[{armenian:"Ծառը մեծ է",english:"The tree is big",level:1}]},
  {id:"nat_006",word:"ծաղիկ",english:["flower"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"nature_environment",lesson_tags:["lesson_8"],frequency_rank:40,examples:[{armenian:"Ծաղիկը գեղեցիկ է",english:"The flower is beautiful",level:1}]},
  {id:"nat_007",word:"երկինք",english:["sky"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"nature_environment",lesson_tags:["lesson_8"],frequency_rank:33,examples:[{armenian:"Երկինքը կապույտ է",english:"The sky is blue",level:1}]},
  {id:"nat_008",word:"ձյուն",english:["snow"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"weather",lesson_tags:["lesson_8"],frequency_rank:42,examples:[{armenian:"Ձյունը սպիտակ է",english:"The snow is white",level:1}]},
  // COLORS
  {id:"col_001",word:"կարմիր",english:["red"],synonyms:[],grammar_type:"adjective",difficulty:1,embedding_group:"colors_appearance",lesson_tags:["lesson_9"],frequency_rank:30,notes:"Armenian flag — top stripe",examples:[{armenian:"Կարմիր ծաղիկը գեղեցիկ է",english:"The red flower is beautiful",level:1}]},
  {id:"col_002",word:"կապույտ",english:["blue"],synonyms:[],grammar_type:"adjective",difficulty:1,embedding_group:"colors_appearance",lesson_tags:["lesson_9"],frequency_rank:31,notes:"Armenian flag — middle stripe",examples:[{armenian:"Երկինքը կապույտ է",english:"The sky is blue",level:1}]},
  {id:"col_003",word:"նարնջագույն",english:["orange","apricot color"],synonyms:[],grammar_type:"adjective",difficulty:1,embedding_group:"colors_appearance",lesson_tags:["lesson_9"],frequency_rank:35,notes:"Armenian flag — bottom stripe",examples:[{armenian:"Ծիրանը նարնջագույն է",english:"The apricot is orange",level:1}]},
  {id:"col_004",word:"սպիտակ",english:["white"],synonyms:[],grammar_type:"adjective",difficulty:1,embedding_group:"colors_appearance",lesson_tags:["lesson_9"],frequency_rank:32,examples:[{armenian:"Ձյունը սպիտակ է",english:"The snow is white",level:1}]},
  {id:"col_005",word:"սև",english:["black"],synonyms:[],grammar_type:"adjective",difficulty:1,embedding_group:"colors_appearance",lesson_tags:["lesson_9"],frequency_rank:33,examples:[{armenian:"Գիշերը սև է",english:"The night is black",level:1}]},
  {id:"col_006",word:"կանաչ",english:["green"],synonyms:[],grammar_type:"adjective",difficulty:1,embedding_group:"colors_appearance",lesson_tags:["lesson_9"],frequency_rank:36,examples:[{armenian:"Խոտը կանաչ է",english:"The grass is green",level:1}]},
  {id:"col_007",word:"դեղին",english:["yellow"],synonyms:[],grammar_type:"adjective",difficulty:1,embedding_group:"colors_appearance",lesson_tags:["lesson_9"],frequency_rank:37,examples:[{armenian:"Արևը դեղին է",english:"The sun is yellow",level:1}]},
  // NUMBERS
  {id:"num_001",word:"մեկ",english:["one","1"],synonyms:[],grammar_type:"numeral",difficulty:1,embedding_group:"numbers_math",lesson_tags:["lesson_9"],frequency_rank:20,examples:[{armenian:"Մեկ հաց",english:"One bread",level:1}]},
  {id:"num_002",word:"երկու",english:["two","2"],synonyms:[],grammar_type:"numeral",difficulty:1,embedding_group:"numbers_math",lesson_tags:["lesson_9"],frequency_rank:21,examples:[{armenian:"Երկու ձու",english:"Two eggs",level:1}]},
  {id:"num_003",word:"երեք",english:["three","3"],synonyms:[],grammar_type:"numeral",difficulty:1,embedding_group:"numbers_math",lesson_tags:["lesson_9"],frequency_rank:22,examples:[{armenian:"Երեք ծառ",english:"Three trees",level:1}]},
  {id:"num_004",word:"չորս",english:["four","4"],synonyms:[],grammar_type:"numeral",difficulty:1,embedding_group:"numbers_math",lesson_tags:["lesson_9"],frequency_rank:23,examples:[{armenian:"Չորս աթոռ",english:"Four chairs",level:1}]},
  {id:"num_005",word:"հինգ",english:["five","5"],synonyms:[],grammar_type:"numeral",difficulty:1,embedding_group:"numbers_math",lesson_tags:["lesson_9"],frequency_rank:24,examples:[{armenian:"Հինգ օր",english:"Five days",level:1}]},
  {id:"num_006",word:"վեց",english:["six","6"],synonyms:[],grammar_type:"numeral",difficulty:1,embedding_group:"numbers_math",lesson_tags:["lesson_9"],frequency_rank:25,examples:[{armenian:"Վեց ժամ",english:"Six hours",level:1}]},
  {id:"num_007",word:"յոթ",english:["seven","7"],synonyms:[],grammar_type:"numeral",difficulty:1,embedding_group:"numbers_math",lesson_tags:["lesson_9"],frequency_rank:26,examples:[{armenian:"Շաբաթը յոթ օր ունի",english:"A week has seven days",level:1}]},
  {id:"num_008",word:"ութ",english:["eight","8"],synonyms:[],grammar_type:"numeral",difficulty:1,embedding_group:"numbers_math",lesson_tags:["lesson_9"],frequency_rank:27,examples:[{armenian:"Ժամը ութն է",english:"It is eight o'clock",level:1}]},
  {id:"num_009",word:"ինը",english:["nine","9"],synonyms:[],grammar_type:"numeral",difficulty:1,embedding_group:"numbers_math",lesson_tags:["lesson_9"],frequency_rank:28,examples:[{armenian:"Ինը ամիս",english:"Nine months",level:1}]},
  {id:"num_010",word:"տասը",english:["ten","10"],synonyms:[],grammar_type:"numeral",difficulty:1,embedding_group:"numbers_math",lesson_tags:["lesson_9"],frequency_rank:29,examples:[{armenian:"Տասը ՀԱՅՔ",english:"Ten HAYQ",level:1}]},
  // GREETINGS
  {id:"greet_001",word:"բարև",english:["hello","hi","bye (informal)"],synonyms:["ողջույն"],grammar_type:"interjection",difficulty:1,embedding_group:"greetings_politeness",lesson_tags:["lesson_1"],frequency_rank:4,examples:[{armenian:"Բարև, ի՞նչ կա",english:"Hello, what's up?",level:1}]},
  {id:"greet_002",word:"ողջույն",english:["greetings","hello (formal)"],synonyms:["բարև"],grammar_type:"interjection",difficulty:1,embedding_group:"greetings_politeness",lesson_tags:["lesson_1"],frequency_rank:14,examples:[{armenian:"Ողջույն, բարև ձեզ",english:"Greetings to you",level:1}]},
  {id:"greet_003",word:"շնորհակալություն",english:["thank you","thanks"],synonyms:[],grammar_type:"interjection",difficulty:1,embedding_group:"greetings_politeness",lesson_tags:["lesson_1"],frequency_rank:16,examples:[{armenian:"Շնորհակալություն, շատ լավ է",english:"Thank you, very good",level:1}]},
  {id:"greet_004",word:"ներողություն",english:["sorry","excuse me"],synonyms:[],grammar_type:"interjection",difficulty:1,embedding_group:"greetings_politeness",lesson_tags:["lesson_1"],frequency_rank:20,examples:[{armenian:"Ներողություն, չհասկացա",english:"Sorry, I didn't understand",level:1}]},
  {id:"greet_005",word:"այո",english:["yes"],synonyms:[],grammar_type:"particle",difficulty:1,embedding_group:"greetings_politeness",lesson_tags:["lesson_1"],frequency_rank:5,examples:[{armenian:"Այո, հասկացա",english:"Yes, I understand",level:1}]},
  {id:"greet_006",word:"ոչ",english:["no"],synonyms:[],grammar_type:"particle",difficulty:1,embedding_group:"greetings_politeness",lesson_tags:["lesson_1"],frequency_rank:6,examples:[{armenian:"Ոչ, չեմ հասկանում",english:"No, I don't understand",level:1}]},
  // ADJECTIVES
  {id:"adj_001",word:"մեծ",english:["big","large","great","old"],synonyms:["խոշոր"],antonyms:["փոքր"],grammar_type:"adjective",difficulty:1,embedding_group:"adjectives_basic",lesson_tags:["lesson_2"],frequency_rank:11,examples:[{armenian:"Տունը մեծ է",english:"The house is big",level:1}]},
  {id:"adj_002",word:"փոքր",english:["small","little","young"],synonyms:[],antonyms:["մեծ"],grammar_type:"adjective",difficulty:1,embedding_group:"adjectives_basic",lesson_tags:["lesson_2"],frequency_rank:17,examples:[{armenian:"Երեխան փոքր է",english:"The child is small",level:1}]},
  {id:"adj_003",word:"լավ",english:["good","well","fine"],synonyms:["բարի","հիանալի"],antonyms:["վատ"],grammar_type:"adjective",difficulty:1,embedding_group:"adjectives_basic",lesson_tags:["lesson_1"],frequency_rank:6,examples:[{armenian:"Շատ լավ է",english:"Very good",level:1}]},
  {id:"adj_004",word:"վատ",english:["bad","poor","wrong"],synonyms:[],antonyms:["լավ"],grammar_type:"adjective",difficulty:1,embedding_group:"adjectives_basic",lesson_tags:["lesson_2"],frequency_rank:19,examples:[{armenian:"Վատ է",english:"It is bad",level:1}]},
  {id:"adj_005",word:"նոր",english:["new"],synonyms:[],antonyms:["հին"],grammar_type:"adjective",difficulty:1,embedding_group:"adjectives_basic",lesson_tags:["lesson_2"],frequency_rank:23,examples:[{armenian:"Սա նոր գիրք է",english:"This is a new book",level:1}]},
  {id:"adj_006",word:"հին",english:["old","ancient"],synonyms:[],antonyms:["նոր"],grammar_type:"adjective",difficulty:1,embedding_group:"adjectives_basic",lesson_tags:["lesson_2"],frequency_rank:24,examples:[{armenian:"Հին քաղաքը գեղեցիկ է",english:"The old city is beautiful",level:2}]},
  {id:"adj_007",word:"շատ",english:["very","much","many","a lot"],synonyms:[],grammar_type:"adverb",difficulty:1,embedding_group:"adjectives_basic",lesson_tags:["lesson_1"],frequency_rank:7,examples:[{armenian:"Շատ եմ սիրում",english:"I love it very much",level:1}]},
  {id:"adj_008",word:"գեղեցիկ",english:["beautiful","gorgeous","lovely"],synonyms:[],grammar_type:"adjective",difficulty:1,embedding_group:"adjectives_basic",lesson_tags:["lesson_2"],frequency_rank:22,examples:[{armenian:"Հայաստանը գեղեցիկ է",english:"Armenia is beautiful",level:1}]},
  {id:"adj_009",word:"առողջ",english:["healthy"],synonyms:[],grammar_type:"adjective",difficulty:1,embedding_group:"health_body",lesson_tags:["lesson_5"],frequency_rank:35,examples:[{armenian:"Ձուկն առողջարար է",english:"Fish is healthy",level:1}]},
  // EDUCATION
  {id:"edu_001",word:"դպրոց",english:["school"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"education_learning",lesson_tags:["lesson_5"],frequency_rank:25,related_forms:["դպրոցում","դպրոցից"],examples:[{armenian:"Ես դպրոց եմ գնում",english:"I am going to school",level:1,acceptable_variants:["Դպրոց եմ գնում"]}]},
  {id:"edu_002",word:"գիրք",english:["book"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"education_learning",lesson_tags:["lesson_5"],frequency_rank:30,related_forms:["գրքի","գրքից","գրքով","գրքում","գրքեր"],examples:[{armenian:"Ես գիրք եմ կարդում",english:"I am reading a book",level:1}]},
  {id:"edu_003",word:"ուսանող",english:["student (university)"],synonyms:["աշակերտ"],grammar_type:"noun",difficulty:1,embedding_group:"education_learning",lesson_tags:["lesson_5"],frequency_rank:28,examples:[{armenian:"Ես ուսանող եմ",english:"I am a student",level:1}]},
  {id:"edu_004",word:"աշակերտ",english:["student (school)","pupil"],synonyms:["ուսանող"],grammar_type:"noun",difficulty:1,embedding_group:"education_learning",lesson_tags:["lesson_5"],frequency_rank:29,examples:[{armenian:"Աշակերտները լավ են սովորում",english:"The students are studying well",level:1}]},
  // PROFESSIONS
  {id:"prof_001",word:"բժիշկ",english:["doctor (male/general)"],synonyms:[],grammar_type:"noun",difficulty:2,embedding_group:"work_profession",lesson_tags:["lesson_8"],frequency_rank:45,gender_note:"masculine/general",examples:[{armenian:"Բժիշկը եկավ",english:"The doctor came",level:1}]},
  {id:"prof_002",word:"բժշկուհի",english:["female doctor"],synonyms:["բժիշկ"],grammar_type:"noun",difficulty:2,embedding_group:"work_profession",lesson_tags:["lesson_8"],frequency_rank:46,gender_note:"feminine",notes:"More natural when referring to female doctor",examples:[{armenian:"Մայրս բժշկուհի է",english:"My mother is a doctor",level:1,acceptable_variants:["Մայրս բժիշկ է","Իմ մայրը բժշկուհի է"]}]},
  {id:"prof_003",word:"ուսուցիչ",english:["teacher (male/general)"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"education_learning",lesson_tags:["lesson_5"],frequency_rank:35,gender_note:"masculine/general",examples:[{armenian:"Հայրս ուսուցիչ է",english:"My father is a teacher",level:1}]},
  {id:"prof_004",word:"ուսուցչուհի",english:["female teacher"],synonyms:["ուսուցիչ"],grammar_type:"noun",difficulty:2,embedding_group:"education_learning",lesson_tags:["lesson_5"],frequency_rank:36,gender_note:"feminine",examples:[{armenian:"Մայրս ուսուցչուհի է",english:"My mother is a teacher",level:1}]},
  // TECHNOLOGY
  {id:"tech_001",word:"հեռախոս",english:["phone","telephone"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"technology",lesson_tags:["lesson_10"],frequency_rank:22,examples:[{armenian:"Իմ հեռախոսը լիցքավորված է",english:"My phone is charged",level:1}]},
  {id:"tech_002",word:"համակարգիչ",english:["computer"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"technology",lesson_tags:["lesson_10"],frequency_rank:25,examples:[{armenian:"Համակարգչով եմ աշխատում",english:"I work with a computer",level:1}]},
  // BODY
  {id:"body_001",word:"գլուխ",english:["head"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"health_body",lesson_tags:["lesson_10"],frequency_rank:38,examples:[{armenian:"Գլուխս ցավում է",english:"My head hurts",level:1}]},
  {id:"body_002",word:"աչք",english:["eye","eyes"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"health_body",lesson_tags:["lesson_10"],frequency_rank:29,examples:[{armenian:"Նրա աչքերը կարմիր են",english:"His/her eyes are red",level:1}]},
  {id:"body_003",word:"ձեռք",english:["hand","arm"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"health_body",lesson_tags:["lesson_10"],frequency_rank:30,examples:[{armenian:"Լվա ձեռքերդ",english:"Wash your hands",level:1}]},
  {id:"body_004",word:"ոտք",english:["leg","foot"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"health_body",lesson_tags:["lesson_10"],frequency_rank:31,examples:[{armenian:"Ոտքս ցավում է",english:"My foot hurts",level:1}]},
];

export const SENTENCE_PATTERNS: SentencePattern[] = [
  {id:"sp_001",english_template:"I am going home",armenian_variants:["Ես գնում եմ տուն","Ես տուն եմ գնում","Տուն եմ գնում","Գնում եմ տուն"],grammar_note:"SOV/SVO both valid. Subject optional.",difficulty:1,lesson_tags:["lesson_2"],semantic_group:"motion_home"},
  {id:"sp_002",english_template:"I am eating bread",armenian_variants:["Ես հաց եմ ուտում","Ես ուտում եմ հաց","Հաց եմ ուտում"],difficulty:1,lesson_tags:["lesson_3"],semantic_group:"eating_food"},
  {id:"sp_003",english_template:"I speak Armenian",armenian_variants:["Ես հայերեն եմ խոսում","Ես խոսում եմ հայերեն","Հայերեն եմ խոսում"],difficulty:1,lesson_tags:["lesson_2"],semantic_group:"language_communication"},
  {id:"sp_004",english_template:"I love Armenia",armenian_variants:["Ես սիրում եմ Հայաստանը","Հայաստանը սիրում եմ","Ես Հայաստանը սիրում եմ"],difficulty:1,lesson_tags:["lesson_4"],semantic_group:"emotions_country"},
  {id:"sp_005",english_template:"I live in Yerevan",armenian_variants:["Ես Երևանում եմ ապրում","Ես ապրում եմ Երևանում","Երևանում եմ ապրում"],difficulty:1,lesson_tags:["lesson_2"],semantic_group:"location_living"},
  {id:"sp_006",english_template:"My mother is a doctor",armenian_variants:["Մայրս բժշկուհի է","Մայրս բժիշկ է","Իմ մայրը բժշկուհի է","Իմ մայրը բժիշկ է","Մայրիկս բժշկուհի է"],grammar_note:"Possessive suffix -s more natural. բժիշկ/բժշկուհի both accepted.",difficulty:1,lesson_tags:["lesson_4"],semantic_group:"family_professions"},
  {id:"sp_007",english_template:"My father is a teacher",armenian_variants:["Հայրս ուսուցիչ է","Իմ հայրը ուսուցիչ է","Հայրիկս ուսուցիչ է","Հայրս ուսուցչուհի է"],grammar_note:"Possessive suffix -s preferred in natural speech",difficulty:1,lesson_tags:["lesson_4"],semantic_group:"family_professions"},
  {id:"sp_008",english_template:"I am reading a book",armenian_variants:["Ես գիրք եմ կարդում","Ես կարդում եմ գիրք","Գիրք եմ կարդում"],difficulty:1,lesson_tags:["lesson_5"],semantic_group:"education_reading"},
  {id:"sp_009",english_template:"How are you?",armenian_variants:["Ինչպե՞ս ես","Ինչպե՞ս ես դու","Ո՞նց ես","Ի՞նչ կա"],grammar_note:"Ո՞նց ես = colloquial. Ինչպե՞ս ես = standard.",difficulty:1,lesson_tags:["lesson_1"],semantic_group:"greetings"},
  {id:"sp_010",english_template:"I am fine",armenian_variants:["Լավ եմ","Ես լավ եմ","Շատ լավ եմ","Ամեն ինչ լավ է"],difficulty:1,lesson_tags:["lesson_1"],semantic_group:"greetings_response"},
  {id:"sp_011",english_template:"Good morning",armenian_variants:["Բարի լույս","Բարի առավոտ","Լավ առավոտ"],grammar_note:"Բարի լույս = traditional. Բարի առավոտ = standard.",difficulty:1,lesson_tags:["lesson_6"],semantic_group:"greetings_time"},
  {id:"sp_012",english_template:"Good night",armenian_variants:["Բարի գիշեր","Անուշ գիշեր"],difficulty:1,lesson_tags:["lesson_6"],semantic_group:"greetings_time"},
  {id:"sp_013",english_template:"How much does it cost?",armenian_variants:["Ի՞նչ արժե","Ինչքա՞ն արժե","Ի՞նչ գին է"],difficulty:2,lesson_tags:["lesson_7"],semantic_group:"shopping"},
  {id:"sp_014",english_template:"My sister is a student",armenian_variants:["Քույրս ուսանող է","Իմ քույրը ուսանող է","Քույրիկս ուսանող է"],difficulty:1,lesson_tags:["lesson_4"],semantic_group:"family_education"},
  {id:"sp_015",english_template:"The sky is blue",armenian_variants:["Երկինքը կապույտ է","Կապույտ է երկինքը"],difficulty:1,lesson_tags:["lesson_8"],semantic_group:"nature_colors"},
  {id:"sp_016",english_template:"It is raining",armenian_variants:["Անձրև է գալիս","Անձրև է","Անձրևոտ է"],difficulty:1,lesson_tags:["lesson_8"],semantic_group:"weather"},
  {id:"sp_017",english_template:"I am learning Armenian",armenian_variants:["Ես հայերեն եմ սովորում","Ես սովորում եմ հայերեն","Հայերեն եմ սովորում"],difficulty:1,lesson_tags:["lesson_1"],semantic_group:"language_learning"},
  {id:"sp_018",english_template:"Armenia is a beautiful country",armenian_variants:["Հայաստանը գեղեցիկ երկիր է","Գեղեցիկ երկիր է Հայաստանը","Հայաստանը շատ գեղեցիկ է"],difficulty:1,lesson_tags:["lesson_1"],semantic_group:"country_culture"},
  {id:"sp_019",english_template:"I drink coffee every morning",armenian_variants:["Ամեն առավոտ սուրջ եմ խմում","Առավոտյան սուրջ եմ խմում","Ես ամեն օր առավոտյան սուրջ եմ խմում"],difficulty:2,lesson_tags:["lesson_6"],semantic_group:"daily_routine_food"},
  {id:"sp_020",english_template:"I want water",armenian_variants:["Ես ուզում եմ ջուր","Ջուր եմ ուզում","Ջուր ուզում եմ"],difficulty:1,lesson_tags:["lesson_3"],semantic_group:"food_desire"},
];

const LEXICON_MAP = new Map<string,LexiconEntry>(LEXICON.map(e=>[e.word,e]));
const ENGLISH_MAP = new Map<string,LexiconEntry[]>();
for(const e of LEXICON){for(const eng of e.english){const k=eng.toLowerCase();if(!ENGLISH_MAP.has(k))ENGLISH_MAP.set(k,[]);ENGLISH_MAP.get(k)!.push(e);}}
export const lookupArmenian=(w:string)=>LEXICON_MAP.get(w);
export const lookupEnglish=(w:string)=>ENGLISH_MAP.get(w.toLowerCase())??[];
export const lookupByCategory=(c:SemanticCategory)=>LEXICON.filter(e=>e.embedding_group===c);
export const lookupSentencePattern=(eng:string)=>SENTENCE_PATTERNS.find(p=>p.english_template.toLowerCase()===eng.toLowerCase());
export const getAllValidArmenianForms=(eng:string)=>lookupSentencePattern(eng)?.armenian_variants??[];
export const getSynonyms=(w:string)=>lookupArmenian(w)?.synonyms??[];
export const LEXICON_STATS={total:LEXICON.length,patterns:SENTENCE_PATTERNS.length,categories:new Set(LEXICON.map(e=>e.embedding_group)).size};
