/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldRouteImport } from './routes/world'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiValidateRouteImport } from './routes/api/validate'

const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiValidateRoute = ApiValidateRouteImport.update({
  id: '/api/validate',
  path: '/api/validate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn': typeof LearnRoute
  '/onboarding': typeof OnboardingRoute
  '/world': typeof WorldRoute
  '/api/validate': typeof ApiValidateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learn': typeof LearnRoute
  '/onboarding': typeof OnboardingRoute
  '/world': typeof WorldRoute
  '/api/validate': typeof ApiValidateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learn': typeof LearnRoute
  '/onboarding': typeof OnboardingRoute
  '/world': typeof WorldRoute
  '/api/validate': typeof ApiValidateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/learn' | '/onboarding' | '/world' | '/api/validate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/learn' | '/onboarding' | '/world' | '/api/validate'
  id: '__root__' | '/' | '/learn' | '/onboarding' | '/world' | '/api/validate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnRoute: typeof LearnRoute
  OnboardingRoute: typeof OnboardingRoute
  WorldRoute: typeof WorldRoute
  ApiValidateRoute: typeof ApiValidateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/validate': {
      id: '/api/validate'
      path: '/api/validate'
      fullPath: '/api/validate'
      preLoaderRoute: typeof ApiValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnRoute: LearnRoute,
  OnboardingRoute: OnboardingRoute,
  WorldRoute: WorldRoute,
  ApiValidateRoute: ApiValidateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
